/*
EXERCISE - 16
UNREGISTERED ACTIVE USERS - 
LIST USERS WHO REGISTERED ON THE PLATFORM IN THE LAST 30 DAYS BUT HAVEN’T REGISTERED FOR ANY EVENTS.
*/

SELECT u.full_name FROM Users u WHERE u.registration_date >= CURDATE() - INTERVAL 30 DAY
AND u.user_id NOT IN (SELECT user_id FROM Registrations)