/*
EXERCISE - 3
INACTIVE USERS - 
RETRIEVE USERS WHO HAVE NOT REGISTERED FOR ANY EVENTS IN THE LAST 90 DAYS
*/

SELECT u.full_name FROM Users u 
WHERE u.user_id NOT IN (SELECT r.user_id FROM Registrations r 
WHERE r.registration_date <= CURDATE() - INTERVAL 90 DAY)
